---

- hosts: all
  remote_user: root
  #become: yes

  roles:
  - { role: cis-centos, when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8")or 
                              (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")}
  - { role: cis-ubuntu, when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20")}

