---

- hosts: all
  remote_user: root
  #become: yes

  tasks:
  - name: install ansible CentOs/RedHat
    yum: 
      name: ansible 
      state: absent
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")or
          (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")or
          (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8")or
          (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")or
          (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")or
          (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")

  - name: install ansible Ubuntu
    apt:  
      name: ansible
      state: absent
    when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20")

